name: Portainer Stack Git Redeploy
author: Julius Freudenberger
description: Action for request to Portainer API for redeploy stack configured to use the docker-compose.yaml from a git repository with pull latest images and possibility to set environment variables

inputs:
  portainerUrl:
    description: 'Portainer URL'
    required: true
  accessToken:
    description: 'Portainer access token'
    required: true
  stackId:
    description: 'Stack ID'
    required: true
  endpointId:
    description: 'Endpoint ID'
    required: false
    default: ''
  environment:
    description: 'Environment variables'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'refresh-ccw'
  color: 'blue'
